<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            <?php if ($this->placeholder("pagetitle") != '') {
                echo $this->placeholder("pagetitle") . ' - ';
            } ?>
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <script src="/js/jquery.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/main.js"></script>

        <!-- Le styles -->
        <link href="/css/bootstrap.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/main.css" rel="stylesheet">
        
        <?php echo $this->headLink(); ?>
        
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">
    <?php echo $this->headScript(); ?>
        
    </head>

    <body>

        <div class="container">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="/">Application</a></a>
                        <div class="nav-collapse">
                            <ul class="nav">
                                <li><a href="/">Search</a></li>
                                <li><a href="/element-group">Element Groups</a></li>
                            </ul>
                            <ul class="nav pull-right">
                                
                                <li><a href="#">Welcome </a></li>
                                <li><a href="/login/out">Log Out</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <?php 
                if(Zend_Controller_Front::getInstance()->getRequest()->getParam("msg")){
            ?>
            <section id="messages">
                <div class="alert alert-success">
                    <a class="close" data-dismiss="alert">×</a>
                    <?= Zend_Controller_Front::getInstance()->getRequest()->getParam("msg"); ?>
                </div>
            </section>
            <?php
                }
            ?>

            <?php 
                if(Zend_Controller_Front::getInstance()->getRequest()->getParam("alert")){
            ?>
            <section id="messages">
                <div class="alert alert-error">
                    <a class="close" data-dismiss="alert">×</a>
                    <?= Zend_Controller_Front::getInstance()->getRequest()->getParam("alert"); ?>
                </div>
            </section>
            <?php
                }
            ?>
            
            <?php echo $this->layout()->content; ?>
            <hr>

            <footer>
                <p>&copy; ZZZZ Inc. <?= date("Y"); ?></p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>